name: torch_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - pip=24.2=py311h06a4308_0
  - python=3.11.9=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==0.33.0
      - adam-mini==1.0.1
      - aiohappyeyeballs==2.3.5
      - aiohttp==3.10.3
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - attrs==24.2.0
      - bitsandbytes==0.43.3
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cupy-cuda12x==13.2.0
      - cython==3.0.11
      - datasets==2.20.0
      - deepspeed==0.14.4
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - fastrlock==0.8.2
      - filelock==3.15.4
      - flash-attn==2.6.3
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - hjson==3.1.0
      - huggingface-hub==0.24.5
      - idna==3.7
      - jinja2==3.1.4
      - lightning==2.4.0
      - lightning-utilities==0.11.6
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.3
      - ninja==1.11.1.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.555.43
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - packaging==24.1
      - pandas==2.2.2
      - pillow==10.4.0
      - platformdirs==4.2.2
      - protobuf==5.27.3
      - psutil==6.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.4.0
      - pytz==2024.1
      - pyyaml==6.0.2
      - regex==2024.7.24
      - requests==2.32.3
      - safetensors==0.4.4
      - sentry-sdk==2.13.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sympy==1.13.2
      - tokenizers==0.19.1
      - torch==2.4.0
      - torchaudio==2.4.0
      - torchmetrics==1.4.1
      - torchvision==0.19.0
      - tqdm==4.66.5
      - transformers==4.44.2
      - triton==3.0.0
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.2
      - wandb==0.17.6
      - xxhash==3.4.1
      - yarl==1.9.4
prefix: /home/rwkv/anaconda3/envs/torch_env
