RWKV:
  layers: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]
  grad_cp: 1

Llama:
  model_id: /data/rwkv/models/meta-llama/Meta-Llama-3.1-8B-Instruct/
is_llama_ffn: True
kl_weight: 0.1
ce_weight: 1
model_file: Llama3.18BInstructRWKV8Layers
teach_mode:
  is_client: True
  nccl_file: nccl.txt
  is_hidden_align: False
  num_groups: 2